In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
df = pd.read_csv('네이버맛집_전처리_3.csv', header='infer', engine='python', encoding='cp949', sep=',')

In [ ]:
for i, url in enumerate(df.loc[:,'images_url']):
    urls = []
    for sp in url.split(','):
#         print(re.sub("]|\[|'", "",sp).strip())
        urls.append([re.sub("]|\[|'", "", sp).strip()])
    df.loc[i, 'images_url_preprocess'] = urls

In [3]:
df.head()

,id,store_name,category,review,tv,biztel,address,Menu,homepage,facebook,...,desc,age10,age20,age30,age40,age50,age60,Female,male,images_url_preprocess
0,1,클로리스 티 앤 커피,홍차전문점,3591,NaN,02-553-7523,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터 지하1층,"5,800원 밀크티\r\n4,800원 허브\r\n4,500원 아메리카노\r\n5,2...",NaN,NaN,...,고풍스러운 인테리어의 티 전문 카페입니다. 순수함을 상징하는 여신의 이름에서 카페 ...,40.03200,78.9417,66.3730,45.4563,30.3777,34.3507,54.0,46.0,['https://search.pstatic.net/common/?autoRotat...
1,2,돝고기506,돼지고기구이,2927,NaN,02-6933-9506,서울 강남구 역삼로17길 53\r\n지번역삼동 739-13,"17,000원 A506 숙성 삼겹살 150g\r\n17,000원 i506 숙성 목살...",https://catchtable.co.kr/widget/reservation?sh...,NaN,...,"돝고기506\r\n저희 돝고기는 21일, 총 506시간을 숙성하고 51번의 과정을 ...",6.92067,81.3200,81.8753,78.1793,44.5760,34.3973,53.0,47.0,['https://search.pstatic.net/common/?autoRotat...
2,3,빌즈 강남,NaN,10527,NaN,02-568-1353,서울 강남구 테헤란로 142\r\n지번역삼동 736-1 아크플레이스 2층,"19,800원 빌즈 리코타 핫케이크\r\n24,000원 풀오지\r\n22,000원 ...",http://www.billskorea.com,NaN,...,"*평일과 주말, 공휴일 모두 오후 1시부터 오후 2시 30분까지 예약을 받지 않습니...",34.54700,76.7583,71.8453,64.2587,45.0967,44.0040,60.0,40.0,['https://search.pstatic.net/common/?autoRotat...
3,4,마마스 역삼점,카페,72,NaN,02-538-1280,서울 강남구 논현로85길 7\r\n지번역삼동 738-6,"13,900원 리코타치즈샐러드\r\n9,800원 모짜렐라 토마토 파니니\r\n7,4...",http://cafemamas.co.kr,NaN,...,"샌드위치 전문 카페 카페마마스의 역삼 점. 간단히 샌드위치, 빵과 음료를 즐길 수 ...",32.32840,99.2662,88.6587,60.7369,41.7760,41.8809,56.0,44.0,['https://search.pstatic.net/common/?autoRotat...
4,5,백제원역삼지에프시점,한식,3047,NaN,02-2051-1122,서울 강남구 테헤란로 152\r\n지번역삼동 737 강남파이낸스센터,"15,000~20,000원 런치정찬\r\n82,000~98,000원 백제원 스페셜 ...",http://didimworld.co.kr/,https://www.facebook.com/DidimDining/,...,NaN,35.75910,80.9862,83.7978,82.9262,94.3298,81.6116,46.0,54.0,['https://search.pstatic.net/common/?autoRotat...

In [4]:
url = df.images_url_preprocess

In [11]:
for i, url in enumerate(df.loc[:,'images_url_preprocess']):
    urls = []
    for sp in url.split(','):
#         print(re.sub("]|\[|'", "",sp).strip())
        urls.append([re.sub("]|\[|'", "", sp).strip()])
    df.loc[i, 'images_url_preprocess'] = urls

In [19]:
news = []
for i in range(len(df.images_url_preprocess)):    
    news.append(df.images_url_preprocess[i][0])

In [23]:
df['new_urls'] = news

In [30]:
df.to_csv('네이버맛집_전처리_3.csv' , index=False , encoding='utf-8-sig')